### ISSUE TITLE
Create a Linux user

### ISSUE THREAD

**Issue by Tvax** [Tvax/seedbox-install#2]
In the fonction `createPlexUser` (line 188) allow the user to choose the username of the new Linux user.

**Comment by jlave-dev** [comment]
I'd be happy to do this! 👍

**Comment by Tvax** [comment]
#### Thank you for your pull request !  
Now all the lines where "plex" appears have to be modified in order to match the right username !

#### Exemple (line 54):
`User=plex` has to be modified to something like this `User=${username}`

Feel free to do it (or not) ;)

**Comment by abhinavralhan** [comment]
I've created a PR for the same :+1:

**Comment by Tvax** [comment]
Still missing some, but thank you !
